### ISSUE TITLE
Validación de datos en API User - Registro

### ISSUE THREAD

**Issue by esteban-anabalon** [Multicaja/api#59]
Entiendo que se está validando rut, email, celular, T&C y pass, 

Rut se validará el formato? la validación contra el Registro Civil es por cada producto?

Según Prepago debería validarse el nombre, sería validar el formato también?

**Comment by pablomarambio** [comment]
- El formato de RUT no se valida en la API. Esto es una pega de la GUI y pueden usarse plugins como, ejem, [éste que hice yo](https://github.com/pablomarambio/jquery.rut).
- Independiente de qué producto invoque la validación contra el SRCeI, el RUT quedará validado para todos
- No validaremos formato de nombre. La forma de validar el nombre consiste en que un usuario interno *borre el nombre que ingresó el usuario y lo reemplace por el que indica su cédula.*

**Comment by pablomarambio** [comment]
Cerraré este issue. El tercer punto lo seguimos discutiendo en #61
